<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_entity_field_access().
 */
function override_node_options_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $entity_type = $field_definition->getTargetEntityTypeId();
  $bundle = $field_definition->getTargetBundle();
  $administer_nodes = $account->hasPermission('administer nodes');

  if ($operation == 'edit' && $entity_type == 'node' && !$administer_nodes) {
     switch ($field_definition->getName()) {
       case 'promote':
         return AccessResult::allowedIfHasPermission($account, "override $bundle promote to front page option");

       case 'sticky':
         return AccessResult::allowedIfHasPermission($account, "override $bundle sticky option");

       case 'revision':
        return AccessResult::allowedIfHasPermission($account, "override $bundle revision option");

       case 'revision_log':
         return AccessResult::allowedIfHasPermission($account, "override $bundle revision log entry");

       case 'created':
         return AccessResult::allowedIfHasPermission($account, "override $bundle authored on option");

       case 'uid':
         return AccessResult::allowedIfHasPermission($account, "override $bundle authored by option");
     }
   }

   return AccessResult::neutral();
 }

/**
 * Implements hook_entity_type_alter().
 */
function override_node_options_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  // Set the node form class to OverrideNodeOptionsNodeForm so that we can
  // override NodeForm::actions() and allow for overriding the publish option.
  $entity_types['node']->setFormClass('default', '\Drupal\override_node_options\OverrideNodeOptionsNodeForm');
  $entity_types['node']->setFormClass('edit', '\Drupal\override_node_options\OverrideNodeOptionsNodeForm');
}
