<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeForm;

/**
 * Implements hook_form_alter().
 */
function override_node_options_form_alter(array &$form, FormStateInterface $form_state) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof NodeForm) {
    /** @var \Drupal\Core\Session\AccountInterface $account */
    $user = \Drupal::currentUser();
    if ($user->hasPermission('administer nodes')) {
      return;
    }

    /** @var \Drupal\node\Entity\Node $node */
    $node = $form_object->getEntity();
    $node_type = $node->getType();

    $form['promote']['#access'] = $user->hasPermission("override $node_type promote to front page option");

    $form['sticky']['#access'] = $user->hasPermission("override $node_type sticky option");

    $form['revision']['#access'] = $user->hasPermission("override $node_type revision option");

    $form['revision_log']['#access'] = $user->hasPermission("override $node_type revision log entry");

    $form['created']['#access'] = $user->hasPermission("override $node_type authored on option");

    $form['uid']['#access'] = $user->hasPermission("override $node_type authored by option");
  }
}
